### ISSUE TITLE
Desktop App: UI styling for confirm access code screen

### ISSUE THREAD

**Issue by jtorreggiani** [specollective/insights-agent-desktop-app#22]
- [x] Background color needs to be #313131
- [x] Enlarge text input and align text [accordingly](https://www.figma.com/file/saSl8LVUCEYpptPsvyGGHq/Insights-Agent?node-id=925%3A1269&t=Xjv5IHPWdesqTEIp-0)
- [x] Correct 'I did not receive a verification code' link
- [x] 'Next' button needs proper alignment with border removed
- [ ] ~Display [tooltip](https://www.figma.com/file/saSl8LVUCEYpptPsvyGGHq/Insights-Agent?node-id=925%3A1269&t=Xjv5IHPWdesqTEIp-0) icon to the right of the text input~ blocked for now, waiting on tooltip content, see #38

**Comment by Saige243** [comment]
Tooltip is blocked for now, waiting on designs.
